### ISSUE TITLE
grafana container permission denied

### ISSUE THREAD

**Issue by dan-burt** [stefanprodan/dockprom#96]
cloned the filesystem & issued command:
ADMIN_USER=admin ADMIN_PASSWORD=admin sudo docker-compose up -d

Errors with:

```
Recreating grafana ... error

ERROR: for grafana  Cannot start service grafana: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/setup.sh\": permission denied": unknown

ERROR: for grafana  Cannot start service grafana: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/setup.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.
```

I have retried after adding "user: root" inside the grafana service of the docker-compose.yml file. Same issue.

**Comment by stefanprodan** [comment]
should be fixed by #97

**Comment by franz101** [comment]
I have the same problem. Tried user "104" / root

**Comment by franz101** [comment]
chmod 755 ./grafana/setup.sh fixed it 👍

**Comment by gbharathkumar** [comment]
i still get the issue mentioned above. 
I have a Oracle VM Toolbox inside which i run my docker containers. 
Still getting the same permission denied issue even after running it as root user. Also executed the above command as well, still no luck. 

Any help would be appreciated?

**Comment by berstend** [comment]
Same issue here, quick fix (`docker-compose.yaml`):

```yaml
(...)
  grafana:
(...)
    entrypoint: chmod 755 ./setup.sh && /setup.sh
(...)
```

😄👍
